// Longevity Interventions Database — April 2026 (Updated April 1, 2026)
// Scores: 0-10 scale per dimension
// Composite = Mechanism(0.25) + Clinical(0.25) + Biomarker(0.20) + Safety(0.15) + Cost(0.15)

const INTERVENTIONS = [
  // === REPROGRAMMING ===
  {
    id: "er100",
    name: "ER-100 (Life Biosciences)",
    category: "reprogramming",
    availability: "clinical",
    stage: "Phase 1 (First-in-Human)",
    stageLabel: "Phase 1",
    organism: "Human (Phase 1), NHP, Mouse",
    mechanism: 9,
    clinical: 6,
    biomarker: 8,
    safety: 4,
    cost: 0,
    mechanismNote: "Partial epigenetic reprogramming via OSK (Oct4/Sox2/Klf4) delivered by AAV. Doxycycline-inducible on/off switch. Restores youthful DNA methylation without full dedifferentiation.",
    clinicalNote: "FDA IND cleared Jan 2026. Phase 1 dosing underway: sentinel patient enrolled with 28-day monitoring before next cohort. Data readout expected Q4 2026 (BIO Investment Summit). NCT07290244. Dose escalation in OAG, then expansion in NAION.",
    biomarkerNote: "NHP data: restored methylation patterns, pERG improvement (visual function). Epigenetic clock reversal in preclinical models.",
    safetyNote: "Novel gene therapy modality — long-term oncogenesis risk unknown. Doxycycline control is a safety feature. 5-year follow-up planned.",
    costNote: "Experimental only. Gene therapy pricing likely >$100K if approved.",
    verdict: "Landmark — the first reprogramming therapy in humans. Incredible science, but years from consumer relevance.",
    sources: ["ClinicalTrials.gov NCT07290244", "Life Biosciences Press Release Jan 2026", "Nature Biotechnology Feb 2026", "BIO Investment Summit Mar 2026: Q4 data readout", "Lifespan.io Feb 2026"]
  },
  {
    id: "altos",
    name: "Altos Labs (Reprogramming Platform)",
    category: "reprogramming",
    availability: "preclinical",
    stage: "Preclinical Research",
    stageLabel: "Preclinical",
    organism: "Mouse, Cell Lines",
    mechanism: 9,
    clinical: 2,
    biomarker: 7,
    safety: 3,
    cost: 0,
    mechanismNote: "Cellular rejuvenation via reprogramming. Belmonte lab Cell 2025 paper showed partial reprogramming reverses mesenchymal drift. Oct 2025: gene silencing prevents cellular drift.",
    clinicalNote: "No clinical trials announced. $3B+ funded, 500 employees. CMO Joan Mannick (mTOR expert) in place. Oct 2025 Cell paper: gene silencing prevents cellular drift. Launched Institute of Computation for AI-guided reprogramming. Reportedly seeking to raise $1B additional.",
    biomarkerNote: "Published epigenetic clock reversal in multiple in vivo models. Computational models for cellular resilience.",
    safetyNote: "Same class-wide oncogenesis concerns as all reprogramming approaches. No human safety data.",
    costNote: "Not accessible. Research institution only.",
    verdict: "Best-funded lab in longevity. World-class science but no clinical timeline. Still a press release.",
    sources: ["PitchBook: Altos Labs $3B+", "Labiotech Mar 2026", "Cell Oct 2025"]
  },
  {
    id: "retro",
    name: "Retro Biosciences",
    category: "reprogramming",
    availability: "clinical",
    stage: "Phase 1 (Autophagy Program)",
    stageLabel: "Phase 1",
    organism: "Human (Phase 1), Mouse",
    mechanism: 8,
    clinical: 6,
    biomarker: 7,
    safety: 4,
    cost: 0,
    mechanismNote: "Dual approach: cellular reprogramming + autophagy activation. Partnered with OpenAI to engineer RetroSOX/RetroKLF variants (50x higher reprogramming markers). RTR242 restores lysosomal function to reactivate cellular cleanup machinery.",
    clinicalNote: "RTR242 Phase 1 first-in-human trial initiated Feb 2026 in Australia. Randomized, double-blind, placebo-controlled in healthy volunteers. Includes exploratory autophagy/lysosomal biomarkers. $1.18B raised (PitchBook).",
    biomarkerNote: "AI-designed Yamanaka factor variants showed improved reprogramming markers in vitro. Autophagy biomarkers being tracked.",
    safetyNote: "RTR242 safety data pending from Phase 1. Autophagy modulation is less risky than direct reprogramming.",
    costNote: "Experimental only.",
    verdict: "Sam Altman–backed moonshot with real clinical progress. The AI-engineered factors are genuinely novel.",
    sources: ["PitchBook: Retro $1.18B", "Labiotech Mar 2026", "FT Jan 2026", "Fight Aging Jan 2026: RTR242 Phase 1 details"]
  },
  {
    id: "chemical-reprog",
    name: "Chemical Reprogramming (Sinclair Cocktails)",
    category: "reprogramming",
    availability: "preclinical",
    stage: "In Vitro / Early Preclinical",
    stageLabel: "Preclinical",
    organism: "Cell Lines, Mouse",
    mechanism: 8,
    clinical: 1,
    biomarker: 7,
    safety: 3,
    cost: 0,
    mechanismNote: "Six chemical cocktails that reverse transcriptomic age in human cells without genetic modification. Published by Sinclair lab (Aging, 2023). Restores NCC and youthful transcript profiles.",
    clinicalNote: "No clinical trials. In vitro proof-of-concept only. Years from human testing.",
    biomarkerNote: "Transcriptomic aging clocks reversed. NCC assay validated. Multi-omics characterization published (eLife, 2024).",
    safetyNote: "Unknown systemic safety. Advantage over genetic approaches: no genome modification. But cocktail effects in vivo untested.",
    costNote: "Research reagents only — not available.",
    verdict: "Exciting proof-of-concept that you can reprogram without genes. But very early — purely academic for now.",
    sources: ["Sinclair et al. Aging 2023", "Mitchell et al. eLife 2024"]
  },

  // === SENOLYTICS ===
  {
    id: "dq",
    name: "Dasatinib + Quercetin (D+Q)",
    category: "senolytic",
    availability: "clinical",
    stage: "Phase 1/2 (Multiple Trials)",
    stageLabel: "Phase 1/2",
    organism: "Human (Multiple Phase 1/2), Mouse, NHP",
    mechanism: 9,
    clinical: 7,
    biomarker: 8,
    safety: 5,
    cost: 3,
    mechanismNote: "First-generation senolytic. Dasatinib (tyrosine kinase inhibitor) + quercetin (flavonoid) transiently disable senescent cell anti-apoptotic pathways (SCAPs). Hit-and-run dosing — half-lives <11 hours.",
    clinicalNote: "Phase 1 completed in diabetic kidney disease (reduced adipose senescent cells). Phase 1 in IPF (improved physical function). SToMP-AD and STAMINA trials in cognitive decline. Phase 2 AD trial underway. Mayo Clinic Phase I trial (NCT07025226) combining D+Q+fisetin+temozolomide for glioma. D+Q senolytics trial for secondary progressive MS (NCT07270120) launched. NEW: EBioMedicine Jan 2026 — D+Q improved kidney function in diabetic mice, reduced p16+ senescent cells, restored α-Klotho and SIRT1, reduced fibrosis/inflammation (NIH-funded).",
    biomarkerNote: "Reduced p16/p21+ cells, SA-β-gal activity, circulating SASP factors (IL-1α, IL-6, MMP-9/12). CSF dasatinib penetrance confirmed (80% in SToMP-AD). Cedars-Sinai Feb 2026: senolytics clear 30-70% of senescent cells; remaining resistant cells may reactivate — 'senosensitizers' concept proposed. D+Q restored geroprotective factors (α-Klotho, SIRT1) in diabetic kidney model.",
    safetyNote: "Dasatinib is FDA-approved for CML — known side effect profile (cytopenia, fluid retention, QT prolongation). Intermittent dosing mitigates chronic toxicity. Quercetin is GRAS. MAJOR SAFETY SIGNAL: PNAS Mar 2026 (UConn) — D+Q causes significant demyelination and oligodendrocyte dysfunction in mouse brains via ER stress/UPR activation. Damage worse in younger mice. Oligodendrocytes shift to immature non-functional state resembling MS lesions. Also: Aging Cell 2026 — D+Q before flu vaccination did NOT improve immune response.",
    costNote: "Dasatinib requires prescription. Quercetin OTC (~$20/mo). Some longevity clinics prescribe D+Q off-label ($200-500/cycle).",
    verdict: "The most clinically validated senolytic combination, but the PNAS 2026 demyelination finding is a serious brain safety concern that warrants caution. Real human data across multiple indications, but CNS effects need investigation.",
    sources: ["Hickson et al. EBioMedicine 2019", "EBioMedicine IPF Phase 1 2023", "Orr — SToMP-AD/STAMINA 2025", "Lombardo et al. PNAS Mar 2026: D+Q demyelination", "Bian et al. EBioMedicine Jan 2026: D+Q kidney/Klotho", "NCT07025226: D+Q+fisetin glioma trial", "NCT07270120: D+Q for SPMS", "Cedars-Sinai Aging Cell Feb 2026: senosensitizers"]
  },
  {
    id: "fisetin",
    name: "Fisetin",
    category: "senolytic",
    availability: "try-now",
    stage: "Phase 1 Pilots / Preclinical",
    stageLabel: "Phase 1 (pilot)",
    organism: "Human (Early Pilots), Rabbit, Mouse",
    mechanism: 7,
    clinical: 4,
    biomarker: 6,
    safety: 7,
    cost: 9,
    mechanismNote: "Naturally occurring flavonoid with senolytic activity. Selectively induces apoptosis in senescent cells. Reduced AF susceptibility in aged rabbits (Heart Rhythm, 2026). Anti-inflammatory and neuroprotective.",
    clinicalNote: "Pilot PK/safety trial underway in healthy volunteers and multimorbid elderly (NCT06431932). Multiple Mayo Clinic-led trials. Phase I glioma trial (NCT07025226) combining fisetin with D+Q and temozolomide — first oncology application of senolytics. No Phase 2 standalone efficacy data yet. Note: D+Q demyelination finding (PNAS 2026) raises questions about fisetin safety in combination, though standalone fisetin CNS effects untested.",
    biomarkerNote: "Reduced p16/p21+ cells in animal models. Decreased senescent cell burden in rhesus monkeys (with D). PK data being collected in ongoing human trial. Cedars-Sinai Feb 2026: senolytic-resistant cells may need 'senosensitizers' for complete clearance.",
    safetyNote: "Naturally occurring in strawberries. OTC supplement. Low oral bioavailability (7.8-31.7%). No serious adverse events reported in animal studies.",
    costNote: "OTC supplement: $15-40/month. Widely available. No prescription needed.",
    verdict: "Best risk/reward for the self-experimenter. Cheap, safe, genuinely senolytic — but human efficacy data is still thin.",
    sources: ["Sengun et al. Heart Rhythm 2026", "NCT06431932", "NCT07025226: glioma senolytic trial", "Colman et al. D+fisetin in NHP"]
  },
  {
    id: "unity-ubx",
    name: "UBX1325 (Unity Biotechnology)",
    category: "senolytic",
    availability: "preclinical",
    stage: "Phase 2b Complete / Company Winding Down",
    stageLabel: "Winding Down",
    organism: "Human (Phase 2b Complete)",
    mechanism: 7,
    clinical: 3,
    biomarker: 5,
    safety: 5,
    cost: 0,
    mechanismNote: "BCL-xL inhibitor targeting senescent cells in retinal disease. Unity pivoted from UBX0101 (failed Phase 2 in OA) to ophthalmology.",
    clinicalNote: "ASPIRE Phase 2b complete: UBX1325 non-inferior to aflibercept at 36 weeks in DME. BUT company shutting down operations — entire workforce laid off, evaluating strategic alternatives as of May 2025. Now privately held (PitchBook Feb 2026).",
    biomarkerNote: "Ophthalmology endpoints: visual acuity, retinal thickness. Less focus on systemic aging biomarkers.",
    safetyNote: "BCL-xL inhibitors carry platelet toxicity risk. Intravitreal delivery limits systemic exposure.",
    costNote: "Experimental only.",
    verdict: "Positive trial data but a dead company. UBX1325 showed non-inferiority to standard of care in DME, but Unity laid off its entire workforce and is winding down. The science worked; the business didn't.",
    sources: ["BioSpace May 2025: ASPIRE 36-week results + workforce reduction", "PitchBook: Unity now privately held Feb 2026", "Retinal Physician Apr 2025"]
  },

  // === PHARMACOLOGICAL ===
  {
    id: "rapamycin",
    name: "Rapamycin (Sirolimus)",
    category: "pharmacological",
    availability: "try-now",
    stage: "FDA-Approved (Transplant) / Off-Label Longevity",
    stageLabel: "Approved (off-label)",
    organism: "Human (Approved), Mouse, Rat, NHP, Multiple Species",
    mechanism: 9,
    clinical: 9,
    biomarker: 8,
    safety: 5,
    cost: 4,
    mechanismNote: "mTOR inhibitor. 167-study meta-analysis (Aging Cell, 2025): extends lifespan comparable to dietary restriction. Delays cancer, neurodegeneration, cardiac aging in mice. 9-14% lifespan extension in mice.",
    clinicalNote: "FDA-approved for organ transplant rejection, TSC. PEARL trial 48-week results (Aging, Apr 2025): primary endpoint (visceral fat) NEGATIVE. Secondary signals: lean tissue mass improved in women at 10mg (p=0.013), self-reported pain improved (p=0.015), general health improved at 5mg. Safe for 1 year — no immunosuppression/metabolic red flags. NIA-funded UT Health San Antonio mega-trial launched Mar 2026 — largest rapamycin-for-aging study to date (84 adults, daily vs intermittent dosing). Also testing semaglutide and dapagliflozin comparator arms.",
    biomarkerNote: "Modulates mTOR/AMPK/autophagy axis. Aging Cell 2026: low-dose rapamycin (1mg/day, 4 months) reduces p21 senescence marker and DNA damage (gammaH2AX) in human immune cells in vivo. However, PEARL trial (n=24 subset) showed NO significant epigenetic clock changes (TruAge) at 48 weeks. Gut dysbiosis signal at 10mg in males.",
    safetyNote: "Known immunosuppressant — infections, mouth ulcers, metabolic effects at transplant doses. Low/intermittent dosing for longevity may mitigate. Requires monitoring.",
    costNote: "Generic available. ~$50-150/month for low-dose. Requires prescription and blood monitoring. Available via longevity clinics.",
    verdict: "The best-evidenced pharmacological longevity intervention. PEARL missed its primary endpoint but confirmed safety for 1 year and showed signals in lean mass and pain. The UT mega-trial is the next definitive test.",
    sources: ["Moel et al. Aging Apr 2025: PEARL 48-week full results (NCT04488601)", "167-study meta-analysis Aging Cell 2025", "Kell et al. Aging Cell 2026: p21 reduction in vivo", "UT Health San Antonio Mar 2026: NIA-funded rapamycin mega-trial", "Food Med Center review Feb 2026"]
  },
  {
    id: "metformin",
    name: "Metformin",
    category: "pharmacological",
    availability: "try-now",
    stage: "FDA-Approved (T2D) / TAME Trial Ongoing",
    stageLabel: "Approved (off-label)",
    organism: "Human (Approved), Mouse, Rat",
    mechanism: 7,
    clinical: 7,
    biomarker: 6,
    safety: 9,
    cost: 9,
    mechanismNote: "AMPK activator → mTOR suppression. Hits more hallmarks of aging than any other drug (per Barzilai). But 2025 meta-analysis: does NOT significantly extend lifespan in healthy vertebrates. MET-PREVENT trial: no improvement in grip strength, walking speed.",
    clinicalNote: "TAME trial (3,000+ patients, 14 sites) ongoing — results expected late 2020s. Observational data: 18% higher median survival in diabetics vs non-diabetics. But selection bias concerns.",
    biomarkerNote: "Broad but modest effects on inflammation, glucose metabolism, cellular senescence. No dramatic aging clock reversal demonstrated.",
    safetyNote: "Decades of safety data. GI side effects common but manageable. B12 depletion with chronic use. Extremely well-characterized.",
    costNote: "Cheapest drug in the formulary. ~$4-10/month generic. Easy to obtain off-label.",
    verdict: "Safe, cheap, widely available. But the longevity-specific evidence is weaker than the hype suggests. TAME trial is the definitive test.",
    sources: ["AFAR TAME Trial", "Barzilai interview Lifespan.io 2025", "Aging Cell 2025 meta-analysis", "ScienceDirect uncertainty review"]
  },
  {
    id: "mdi2517",
    name: "MDI-2517 (PAI-1 Inhibitor, Juvenescence)",
    category: "pharmacological",
    availability: "clinical",
    stage: "Phase 1 Complete (Jan 2026) → Phase 2 H2 2026",
    stageLabel: "Phase 1 → 2",
    organism: "Human (Phase 1 Complete)",
    mechanism: 8,
    clinical: 6,
    biomarker: 7,
    safety: 5,
    cost: 0,
    mechanismNote: "Plasminogen Activator Inhibitor-1 (PAI-1) inhibitor. Human genetics: Amish community with PAI-1 loss-of-function mutation live ~10 years longer. PAI-1 elevated in aging, fibrosis, metabolic syndrome.",
    clinicalNote: "Phase 1 completed Jan 2026: good safety/tolerability, once-daily oral dosing confirmed. Phase 2 PoC planned H2 2026 targeting chronic kidney disease and interstitial lung disease. MDI Therapeutics: $9.6M raised. First-in-class PAI-1 inhibitor.",
    biomarkerNote: "PAI-1 levels directly measurable. Fibrosis and metabolic biomarkers relevant. Human genetic validation is the gold standard.",
    safetyNote: "Phase 1 clean. Unknown long-term effects of chronic PAI-1 inhibition. Bleeding risk theoretical concern.",
    costNote: "Experimental only.",
    verdict: "One of the most genetically validated aging targets. The Amish data is compelling. Phase 2 will be the real test.",
    sources: ["BioSpace Feb 2026", "Longevity.Technology Mar 2026", "PitchBook: MDI Therapeutics", "LinkedIn: Parris Longevity Accelerator Mar 2026"]
  },
  {
    id: "glp1",
    name: "GLP-1 Agonists (Semaglutide/Tirzepatide)",
    category: "pharmacological",
    availability: "try-now",
    stage: "FDA-Approved (Obesity/T2D)",
    stageLabel: "Approved",
    organism: "Human (Approved)",
    mechanism: 7,
    clinical: 9,
    biomarker: 8,
    safety: 7,
    cost: 3,
    mechanismNote: "GLP-1/GIP receptor agonists. Primary: weight loss, glucose control. Emerging: cardiovascular protection (SELECT trial 20% MACE reduction), potential anti-inflammatory, possible neuroprotective. Not designed as anti-aging but hitting aging hallmarks.",
    clinicalNote: "Massive Phase 3 programs. SURPASS, STEP, SELECT trials. FDA-approved for obesity and T2D. Being studied for MASH, heart failure, CKD, Alzheimer's. Microdosing trend: ~1 in 7 users microdosing for longevity/healthspan (Evidation survey Mar 2026). PubMed Mar 2026 UK cohort modeling — semaglutide predicted to add 1.9 years life expectancy. NEW: NCT07293325 launched — first dedicated aging biomarker trial comparing semaglutide vs tirzepatide vs metformin on DNA methylation age (66 adults, 24 weeks). Also included in UT Health rapamycin mega-trial as a comparator arm.",
    biomarkerNote: "Weight loss, HbA1c, cardiovascular events, inflammatory markers. NEW: SLIM LIVER post-hoc (Research Square 2025) — semaglutide modulated DunedinPACE (epigenetic pace of aging) in 41.5% of participants, with responders showing greater liver fat reduction (p=0.024) and improved gait speed. First evidence of GLP-1 effects on validated aging clocks.",
    safetyNote: "GI side effects common (nausea, vomiting). Pancreatitis risk. Muscle mass loss concerns. Well-monitored given massive patient exposure.",
    costNote: "$500-1,300/month without insurance. Compounding pharmacies ~$200-400/month. Insurance coverage variable.",
    verdict: "Not designed for longevity but may be the most impactful healthspan drug of the decade. Metabolic benefits are massive and well-proven.",
    sources: ["SELECT trial results", "FDA approvals 2023-2025", "Science News Mar 2026: GLP-1 microdosing longevity", "SLIM LIVER post-hoc Research Square 2025: DunedinPACE modulation", "NCT07293325: semaglutide vs tirzepatide vs metformin aging trial", "PubMed Mar 2026: semaglutide +1.9yr life expectancy modeling"]
  },

  // === SUPPLEMENTS ===
  {
    id: "nmn",
    name: "NMN (Nicotinamide Mononucleotide)",
    category: "supplement",
    availability: "try-now",
    stage: "Human RCTs (NAD+ endpoint)",
    stageLabel: "Human RCTs",
    organism: "Human (Multiple RCTs)",
    mechanism: 7,
    clinical: 5,
    biomarker: 7,
    safety: 8,
    cost: 6,
    mechanismNote: "NAD+ precursor → Sirtuin activation → improved mitochondrial function. Nature Metabolism 2026: NMN and NR both ~2x circulating NAD+ after 14 days. Gut bacteria convert NMN to nicotinic acid for systemic NAD+ boost.",
    clinicalNote: "Multiple small human RCTs showing NAD+ elevation. Nature Metabolism 2026 head-to-head: NMN and NR both ~2x NAD+ at 14 days, while nicotinamide (Nam) only works acutely. NMNH (reduced form) triples NAD+ in first human trial (unpublished, 80 adults, 90 days). Still no hard clinical longevity endpoints.",
    biomarkerNote: "Reliably raises blood NAD+ levels ~2-fold. Increases short-chain fatty acids (SCFA). But brain NAD+ not elevated at 8 days. Surrogate, not clinical, endpoints.",
    safetyNote: "Well-tolerated in trials. OTC supplement. No serious adverse events reported. Long-term safety unknown at high doses.",
    costNote: "Quality varies wildly. $40-120/month for 500mg-1g/day from reputable brands.",
    verdict: "Reliably raises NAD+. But NAD+ is a biomarker, not a clinical outcome. The longevity claims outrun the evidence.",
    sources: ["Cuenoud et al. Nature Metabolism 2026", "nmn.com review", "NAD.com Jan 2026: NMNH trial results"]
  },
  {
    id: "nr",
    name: "NR (Nicotinamide Riboside)",
    category: "supplement",
    availability: "try-now",
    stage: "Human RCTs (NAD+ endpoint)",
    stageLabel: "Human RCTs",
    organism: "Human (Multiple RCTs), Mouse",
    mechanism: 7,
    clinical: 5,
    biomarker: 7,
    safety: 8,
    cost: 6,
    mechanismNote: "NAD+ precursor like NMN. Norway study (2026): NR raised blood NAD+ 2.3x more than NMN at 8 days. After 4 weeks, NR raised brain NAD+ in healthy individuals (not in Parkinson's patients).",
    clinicalNote: "Lancet eClinicalMedicine 2025: Phase I in Parkinson's — enhanced NAD+ metabolome, upregulated mitochondrial respiration. Nature Metabolism 2026 head-to-head confirms NR comparable to NMN for NAD+ elevation. Key finding: gut bacteria convert NR to nicotinic acid for systemic NAD+ boost. Also increases short-chain fatty acids (SCFAs).",
    biomarkerNote: "Raises blood NAD+ (possibly more than NMN per Norway study). Brain NAD+ elevation after 4 weeks. Parkinson's trial: improved mitochondrial function markers.",
    safetyNote: "GRAS status (Niagen). Well-tolerated across multiple trials. ChromaDex/Tru Niagen is the main commercial source.",
    costNote: "$40-80/month for standard dosing (300-1000mg/day).",
    verdict: "May be slightly superior to NMN for NAD+ elevation. Brain penetrance is interesting. But same limitation: surrogate endpoint, not lifespan.",
    sources: ["Cuenoud et al. Nature Metabolism 2026: head-to-head", "Lancet eClinMed 2025 Parkinson's", "Norway NR vs NMN study 2026"]
  },
  {
    id: "quercetin",
    name: "Quercetin (Standalone)",
    category: "supplement",
    availability: "try-now",
    stage: "OTC Supplement / Clinical Trials (with D)",
    stageLabel: "OTC / trials",
    organism: "Human (in D+Q trials), Mouse",
    mechanism: 5,
    clinical: 4,
    biomarker: 4,
    safety: 9,
    cost: 9,
    mechanismNote: "Plant flavonoid with senolytic activity (weaker alone than with dasatinib). Anti-inflammatory, antioxidant. Part of D+Q combination but standalone senolytic effect is modest.",
    clinicalNote: "Primarily studied as part of D+Q. Standalone quercetin trials mostly for anti-inflammatory/antioxidant effects, not senolytic endpoints.",
    biomarkerNote: "Anti-inflammatory markers (IL-6, CRP) may improve. Standalone senolytic biomarker data limited.",
    safetyNote: "GRAS. Present in many fruits/vegetables. Excellent safety profile. Minimal drug interactions at supplement doses.",
    costNote: "$10-25/month. Widely available OTC.",
    verdict: "Cheap, safe, mild anti-inflammatory. But don't expect standalone senolytic miracles — the magic is in the D+Q combo.",
    sources: ["Part of D+Q clinical evidence", "GRAS status"]
  },
  {
    id: "resveratrol",
    name: "Resveratrol",
    category: "supplement",
    availability: "try-now",
    stage: "Failed to Translate / OTC",
    stageLabel: "OTC (weak)",
    organism: "Human (multiple negative RCTs), Mouse",
    mechanism: 4,
    clinical: 3,
    biomarker: 3,
    safety: 8,
    cost: 8,
    mechanismNote: "Sirtuin activator (SIRT1). Initial excitement from Sinclair mouse studies. But poor bioavailability, inconsistent results in humans. GlaxoSmithKline acquired Sirtris for $720M, then shut it down.",
    clinicalNote: "Multiple human RCTs show no consistent benefit on metabolic markers, cardiovascular outcomes, or aging biomarkers. Meta-analyses mixed at best.",
    biomarkerNote: "No consistent epigenetic clock reversal. Inconsistent effects on inflammatory markers. Blood levels hard to maintain therapeutically.",
    safetyNote: "Generally safe. GI discomfort at high doses. Drug interactions possible (CYP metabolism).",
    costNote: "$15-40/month.",
    verdict: "The original longevity supplement hype cycle — and a cautionary tale. The science didn't replicate. Mostly influencer theater now.",
    sources: ["GSK/Sirtris shutdown", "Multiple negative meta-analyses"]
  },
  {
    id: "spermidine",
    name: "Spermidine",
    category: "supplement",
    availability: "try-now",
    stage: "Observational + Small RCTs",
    stageLabel: "Small RCTs",
    organism: "Human (Observational + Small RCTs), Mouse",
    mechanism: 7,
    clinical: 4,
    biomarker: 5,
    safety: 8,
    cost: 7,
    mechanismNote: "Autophagy inducer via hypusination of eIF5A. Nature Reviews 2026: spermidine feeding increased median lifespan ~10-15% in mice. Observational data: higher dietary spermidine intake associated with ~40% reduced fatal heart failure risk and lower all-cause mortality.",
    clinicalNote: "SmartAge trial: 3-month spermidine supplementation improved memory in older adults at risk of dementia. But small sample size. Observational longevity association.",
    biomarkerNote: "Autophagy markers, memory scores, cardiac biomarkers in preclinical. Limited validated aging biomarkers in human trials.",
    safetyNote: "Naturally occurring polyamine. Found in wheat germ, soybeans, aged cheese. Well-tolerated in trials.",
    costNote: "$30-60/month for supplements. Also available through diet (wheat germ).",
    verdict: "Interesting mechanism and observational data. Small human trials are encouraging but not definitive. A reasonable low-risk bet.",
    sources: ["SmartAge trial", "Nature Reviews 2026 spermidine review", "Oxford Healthspan Feb 2026 review", "Epidemiological mortality association"]
  },

  // === LIFESTYLE ===
  {
    id: "sauna",
    name: "Sauna (Finnish-Style Heat Therapy)",
    category: "lifestyle",
    availability: "try-now",
    stage: "Epidemiological (Large Cohorts)",
    stageLabel: "Epidemiological",
    organism: "Human (Prospective Cohorts)",
    mechanism: 7,
    clinical: 6,
    biomarker: 6,
    safety: 8,
    cost: 7,
    mechanismNote: "Heat stress → cardiovascular conditioning (HR 120-150 bpm), endothelial function improvement, blood pressure reduction, autonomic nervous system modulation, natriuretic peptide reduction, anti-inflammatory.",
    clinicalNote: "JAMA 2015: 2,315 Finnish men over 20 years — 4-7x/week sauna users had 63% lower CVD mortality vs 1x/week. BMC Medicine 2018: 1,688 men+women — linear dose-response, 70% CVD reduction at 4-7x/week. HR 0.30 (95% CI 0.14-0.64).",
    biomarkerNote: "Blood pressure, heart rate variability, CRP, left ventricular ejection fraction, BNP levels. CVD mortality risk reclassification improved by 4.14%.",
    safetyNote: "Safe for most adults including stable cardiac patients. Caution in elderly prone to orthostatic hypotension. Avoid with unstable angina.",
    costNote: "Home infrared: $300-3,000 one-time. Gym/spa membership: $50-200/month. Free at many gyms. Finnish-style requires higher temps (175°F+).",
    verdict: "One of the strongest lifestyle interventions for cardiovascular health. The Finnish data is remarkable. The dose-response is clear: more is better.",
    sources: ["JAMA Int Med 2015 Laukkanen", "BMC Medicine 2018", "Harvard Health 2015"]
  },
  {
    id: "cold",
    name: "Cold Exposure / Cold Plunge",
    category: "lifestyle",
    availability: "try-now",
    stage: "Small RCTs + Mechanistic Studies",
    stageLabel: "Small RCTs",
    organism: "Human (Small RCTs), Mouse",
    mechanism: 6,
    clinical: 3,
    biomarker: 5,
    safety: 7,
    cost: 7,
    mechanismNote: "Activates brown adipose tissue (BAT), increases energy expenditure, improves insulin sensitivity. Life Sciences 2025 review: reduces chronic inflammation, enhances antioxidant defenses. Meta-analysis: acute cold increases BAT activity and energy expenditure.",
    clinicalNote: "Small human studies show BAT activation, increased cold-induced thermogenesis. 6-week study: increased BAT, decreased body fat. But NO longevity-specific clinical trials. No hard outcome data.",
    biomarkerNote: "BAT volume/activity (FDG-PET), UCP1 expression, energy expenditure, glucose uptake. Metabolic markers improve but no aging-specific biomarkers validated.",
    safetyNote: "Hypothermia risk if excessive. Cardiac stress possible — cold water immersion triggers sympathetic activation. Not advisable with uncontrolled hypertension or arrhythmias.",
    costNote: "Cold showers: free. Cold plunge: $500-5,000 one-time. Cryotherapy: $30-80/session.",
    verdict: "Real metabolic benefits (BAT activation, inflammation). But the longevity-specific evidence is almost entirely extrapolated from mechanism, not outcomes. Huberman overhyped this.",
    sources: ["Life Sciences 2025 review", "Frontiers Physiology 2022 meta-analysis", "Int J Mol Sci 2024 review"]
  },
  {
    id: "exercise",
    name: "Zone 2 + Resistance Training",
    category: "lifestyle",
    availability: "try-now",
    stage: "Massive Epidemiological + RCT Data",
    stageLabel: "Gold Standard",
    organism: "Human (Thousands of Studies)",
    mechanism: 9,
    clinical: 10,
    biomarker: 9,
    safety: 9,
    cost: 9,
    mechanismNote: "Hits nearly every hallmark of aging: mitochondrial biogenesis, autophagy, senescent cell clearance, telomere maintenance, inflammation reduction, insulin sensitivity, muscle protein synthesis. The single most validated anti-aging intervention.",
    clinicalNote: "Epidemiological: 3-5 years additional life expectancy. Reduces all-cause mortality 30-50%. Reduces risk of virtually every age-related disease. Hundreds of RCTs.",
    biomarkerNote: "VO2max (strongest predictor of all-cause mortality), muscle mass, bone density, HbA1c, blood pressure, inflammatory markers, epigenetic age.",
    safetyNote: "Overwhelmingly safe when properly programmed. Injury risk manageable. Beneficial even for frail elderly.",
    costNote: "Free (bodyweight exercises, walking, running). Gym: $20-80/month. Personal training optional.",
    verdict: "The undisputed champion. Nothing else comes close for evidence quality. If you're not doing this, no supplement will save you.",
    sources: ["Hundreds of systematic reviews and meta-analyses"]
  },
  {
    id: "caloric-restriction",
    name: "Caloric Restriction / Time-Restricted Eating",
    category: "lifestyle",
    availability: "try-now",
    stage: "Human RCTs + NHP Studies",
    stageLabel: "Human RCTs",
    organism: "Human (CALERIE trial), NHP (20+ year studies), Mouse",
    mechanism: 8,
    clinical: 7,
    biomarker: 7,
    safety: 6,
    cost: 10,
    mechanismNote: "Activates AMPK, inhibits mTOR, upregulates sirtuins and autophagy. CALERIE trial: 25% CR for 2 years reduced cardiometabolic risk factors, slowed biological aging. NHP: extended lifespan in Wisconsin study.",
    clinicalNote: "CALERIE is the landmark human CR trial — reduced systemic inflammation, improved metabolic markers. Time-restricted eating (16:8) has weaker evidence but some metabolic benefits.",
    biomarkerNote: "DunedinPACE biological aging clock slowed. Insulin sensitivity, inflammatory markers, body composition all improved.",
    safetyNote: "Muscle mass loss risk, bone density concerns, potential for disordered eating. Not appropriate for underweight or elderly. Compliance is the biggest challenge.",
    costNote: "Saves money (eating less). Free.",
    verdict: "Strong evidence across species. The gold standard for dietary intervention. But most people can't sustain 25% CR — hence the search for CR mimetics.",
    sources: ["CALERIE trial", "Wisconsin NHP study", "Aging Cell 2025 meta-analysis"]
  },
  {
    id: "sleep",
    name: "Sleep Optimization (7-9 hrs)",
    category: "lifestyle",
    availability: "try-now",
    stage: "Epidemiological + Mechanistic",
    stageLabel: "Epidemiological",
    organism: "Human (Large Cohorts)",
    mechanism: 8,
    clinical: 7,
    biomarker: 7,
    safety: 10,
    cost: 10,
    mechanismNote: "Glymphatic clearance of brain waste (amyloid-β, tau), growth hormone release, DNA repair, immune restoration, cortisol regulation. Sleep deprivation accelerates virtually every aging biomarker.",
    clinicalNote: "Epidemiological: <6 hrs/night associated with 12% increased all-cause mortality. Poor sleep quality linked to accelerated biological aging across multiple clock measures.",
    biomarkerNote: "Cortisol, inflammatory cytokines, glucose metabolism, epigenetic age acceleration, cognitive function, telomere length.",
    safetyNote: "No risks from getting good sleep. The opposite of a drug — it's the absence of a toxin (sleep deprivation).",
    costNote: "Free. Better sleep hygiene costs nothing. Mattress/environment optimization: optional investment.",
    verdict: "The most underrated longevity intervention. Free, universally beneficial, and most people are chronically underperforming here.",
    sources: ["Large epidemiological cohorts", "Glymphatic system research"]
  },

  // === INFLUENCER THEATER ===
  {
    id: "peptides-random",
    name: "Peptide Cocktails (BPC-157, TB-500, etc.)",
    category: "supplement",
    availability: "try-now",
    stage: "No Human Longevity Data",
    stageLabel: "Unregulated",
    organism: "Rat/Mouse (injury models)",
    mechanism: 4,
    clinical: 1,
    biomarker: 2,
    safety: 3,
    cost: 4,
    mechanismNote: "BPC-157: gastric pentadecapeptide studied for injury healing in rodents. TB-500: thymosin beta-4 fragment. Mechanisms are injury-repair, NOT anti-aging. No established longevity pathway.",
    clinicalNote: "Zero human clinical trials for longevity endpoints. All human use is gray-market self-experimentation. BPC-157 studies are almost exclusively rat/mouse injury models.",
    biomarkerNote: "No validated aging biomarkers studied. Injury healing endpoints only.",
    safetyNote: "Unregulated manufacturing. Contamination risk. No long-term safety data. FDA has warned about peptide marketing. Self-injection risks.",
    costNote: "$50-200/month from gray-market sources.",
    verdict: "Pure influencer theater. These are injury-repair peptides being marketed as anti-aging. No longevity mechanism, no human data, no quality control.",
    sources: ["FDA warnings on peptide marketing", "Rodent injury model studies only"]
  },
  {
    id: "nad-iv",
    name: "NAD+ IV Infusions",
    category: "supplement",
    availability: "try-now",
    stage: "No Controlled Trials for Longevity",
    stageLabel: "Clinic marketing",
    organism: "Human (uncontrolled)",
    mechanism: 5,
    clinical: 1,
    biomarker: 3,
    safety: 6,
    cost: 1,
    mechanismNote: "Direct NAD+ infusion bypasses oral absorption issues. But NAD+ is rapidly metabolized — IV bolus may not have sustained effect. Mechanism is the same as NMN/NR but at much higher cost.",
    clinicalNote: "No controlled clinical trials for longevity or aging endpoints. Offered at boutique wellness clinics based on NAD+ biology extrapolation.",
    biomarkerNote: "Acutely raises blood NAD+ (obviously). But no evidence this produces better outcomes than oral NMN/NR supplementation.",
    safetyNote: "IV access risks (infection, phlebitis). Side effects during infusion: flushing, nausea, chest tightness. Generally safe in clinical setting.",
    costNote: "$500-1,500 per infusion. Clinics recommend weekly-monthly. $2,000-6,000+/year.",
    verdict: "Expensive way to achieve what a $50/month NMN supplement does. The boutique clinic premium is for the experience, not the science.",
    sources: ["No published controlled trials", "Clinical marketing only"]
  },
  {
    id: "hyperbaric",
    name: "Hyperbaric Oxygen Therapy (HBOT)",
    category: "lifestyle",
    availability: "try-now",
    stage: "Small RCTs / Exploratory",
    stageLabel: "Small RCTs",
    organism: "Human (Small Studies)",
    mechanism: 5,
    clinical: 3,
    biomarker: 4,
    safety: 6,
    cost: 2,
    mechanismNote: "Hyperoxia-hypoxia cycling may trigger regenerative pathways, stem cell mobilization, and telomere elongation. One small Israeli study (Shai Efrati) showed telomere lengthening and senescent cell reduction.",
    clinicalNote: "The Efrati 2020 study (35 healthy elderly, 60 sessions) is the main longevity evidence. Small, single-center, no replication. FDA-approved for wound healing, decompression sickness — not aging.",
    biomarkerNote: "Telomere length (controversial measurement), senescent cell markers, cognitive function in small studies.",
    safetyNote: "Barotrauma risk (ear, sinus), oxygen toxicity (seizures) at high pressures. Claustrophobia. Generally safe at clinical pressures.",
    costNote: "$100-300/session. Protocols require 40-60 sessions. Total: $4,000-18,000.",
    verdict: "One intriguing but unreplicated study driving a massive wellness industry. The cost-to-evidence ratio is terrible.",
    sources: ["Efrati et al. Aging 2020", "FDA approved indications"]
  }
];

// Calculate composite scores
INTERVENTIONS.forEach(d => {
  d.composite = +(d.mechanism * 0.25 + d.clinical * 0.25 + d.biomarker * 0.20 + d.safety * 0.15 + d.cost * 0.15).toFixed(1);
});

// Sort by composite desc
INTERVENTIONS.sort((a, b) => b.composite - a.composite);
